#!/usr/bin/env node
// Stand-in for the OrcaSlicer CLI in tests: validates arguments and writes a small G-code.
import fs from 'node:fs';
import path from 'node:path';
const args = process.argv.slice(2);
const opt = (name) => args[args.indexOf(name) + 1];
const outDir = opt('--outputdir');
const models = args.filter((a) => /\.(stl|3mf|obj)$/i.test(a));
const machine = JSON.parse(fs.readFileSync('machine.json', 'utf8'));
const proc = JSON.parse(fs.readFileSync('process.json', 'utf8'));
fs.writeFileSync('args.json', JSON.stringify(args));
if (proc.name === 'FAIL') {
  fs.writeFileSync(path.join(outDir, 'result.json'), JSON.stringify({ return_code: -17, error_string: 'The selected printer is not compatible with the process preset in the 3mf.' }));
  process.exit(239);
}
/** Bounding box of a binary STL, to check where parts were placed. */
const bounds = (file) => {
  if (file.endsWith('.3mf')) return '3mf';
  const b = fs.readFileSync(file);
  const n = b.readUInt32LE(80);
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < n * 9; i++) {
    const v = b.readFloatLE(84 + Math.floor(i / 9) * 50 + 12 + (i % 9) * 4);
    min[i % 3] = Math.min(min[i % 3], v);
    max[i % 3] = Math.max(max[i % 3], v);
  }
  return [...min, ...max].map((v) => Math.round(v * 10) / 10).join(',');
};
const gcode = [
  '; HEADER_BLOCK_START',
  '; generated by OrcaSlicer 2.4.2',
  `; total layers count = ${Math.round(20 / Number(proc.layer_height ?? 0.2))}`,
  '; HEADER_BLOCK_END',
  '',
  `; printer = ${machine.name}`,
  `; copies = ${models.length}`,
  `; models = ${models.map((m) => path.basename(m)).join(',')}`,
  `; bounds = ${models.map(bounds).join(' | ')}`,
  `; arrange = ${opt('--arrange')}`,
  `; curr_bed_type = ${proc.curr_bed_type} / ${machine.curr_bed_type}`,
  `; enable_support = ${proc.enable_support}`,
  `; support_type = ${proc.support_type}`,
  `; brim_type = ${proc.brim_type}`,
  `; brim_width = ${proc.brim_width}`,
  `; skirt_loops = ${proc.skirt_loops}`,
  `; spiral_mode = ${proc.spiral_mode}`,
  `; wall_loops = ${proc.wall_loops}`,
  `; sparse_infill_density = ${proc.sparse_infill_density}`,
  `; sparse_infill_pattern = ${proc.sparse_infill_pattern}`,
  'G28',
  'M83',
  ';TYPE:Skirt',
  'G1 X100 Y100 F3000',
  'G1 X120 Y100 E1',
  'G1 X120 Y120 E1',
  ';TYPE:Outer wall',
  'G1 X105 Y105 Z0.2',
  'G1 X115 Y105 E.5',
  'G2 X115 Y115 I0 J5 E.5',
  'G1 X105 Y115 E.5',
  'G1 X10 Y10',
  '; filament used [mm] = 1234.5',
  '; total filament used [g] = 3.70',
  '; estimated printing time (normal mode) = 1h 2m 3s',
  '',
].join('\n');
fs.writeFileSync(path.join(outDir, 'plate_1.gcode'), gcode);
fs.writeFileSync(path.join(outDir, 'result.json'), JSON.stringify({ return_code: 0, error_string: 'Success.' }));
console.log('sliced', models.length);
