#!/usr/bin/env node
// Stand-in for the OrcaSlicer CLI in tests: validates arguments and writes a small G-code.
import fs from 'node:fs';
import path from 'node:path';
const args = process.argv.slice(2);
const opt = (name) => args[args.indexOf(name) + 1];
const outDir = opt('--outputdir');
const models = args.filter((a) => /\.(stl|3mf|obj)$/i.test(a));
const machine = JSON.parse(fs.readFileSync('machine.json', 'utf8'));
const proc = JSON.parse(fs.readFileSync('process.json', 'utf8'));
fs.writeFileSync('args.json', JSON.stringify(args));
if (proc.name === 'FAIL') {
  fs.writeFileSync(path.join(outDir, 'result.json'), JSON.stringify({ return_code: -17, error_string: 'The selected printer is not compatible with the process preset in the 3mf.' }));
  process.exit(239);
}
const gcode = [
  '; HEADER_BLOCK_START',
  '; generated by OrcaSlicer 2.4.2',
  `; total layers count = ${Math.round(20 / Number(proc.layer_height ?? 0.2))}`,
  '; HEADER_BLOCK_END',
  '',
  `; printer = ${machine.name}`,
  `; copies = ${models.length}`,
  'G28',
  'G1 X10 Y10',
  '; filament used [mm] = 1234.5',
  '; total filament used [g] = 3.70',
  '; estimated printing time (normal mode) = 1h 2m 3s',
  '',
].join('\n');
fs.writeFileSync(path.join(outDir, 'plate_1.gcode'), gcode);
fs.writeFileSync(path.join(outDir, 'result.json'), JSON.stringify({ return_code: 0, error_string: 'Success.' }));
console.log('sliced', models.length);
